% Autogenerated data feature matrix
for regListIndex = 1:length(train_true_regs_1contMet) 

    tarFlux = regListIndex;
    met1 = 1+2*(regListIndex-1);
    
    % Correlation of single metabolite with target flux
    featureMatrix_AutoGenerateTrain_1contMet(1,regListIndex) = feature_correlation_1contMet_median(autogen_prefix,met1,tarFlux,num_IC,nT,cov,rep);

    % Curve fit adjusted R2
    featureMatrix_AutoGenerateTrain_1contMet(2,regListIndex) = feature_curveFit_1contMet_median(autogen_prefix,met1,tarFlux,num_IC,nT,cov,rep);

    % Predict flux with machine learning
    featureMatrix_AutoGenerateTrain_1contMet(3,regListIndex) = feature_predictFlux_1contMet_median(autogen_prefix,met1,tarFlux,num_IC,nT,cov,rep);

    % CoV of metabolite vs flux data
    featureMatrix_AutoGenerateTrain_1contMet(4,regListIndex) = feature_cov_1contMet_median(autogen_prefix,met1,tarFlux,num_IC,nT,cov,rep);
end
featureMatrix_AutoGenerateTrain_1contMet_n = normalize(featureMatrix_AutoGenerateTrain_1contMet,2,'range');

% Second autogenerated data feature matrix
for regListIndex = 1:length(train_true_regs_meta_1contMet) 

    tarFlux = regListIndex;
    met1 = 1+2*(regListIndex-1);
    
    % Correlation of single metabolite with target flux
    featureMatrix_AutoGenerateTrain_meta_1contMet(1,regListIndex) = feature_correlation_1contMet_median(autogen_meta_prefix,met1,tarFlux,num_IC,nT,cov,rep);

    % Curve fit adjusted R2
    featureMatrix_AutoGenerateTrain_meta_1contMet(2,regListIndex) = feature_curveFit_1contMet_median(autogen_meta_prefix,met1,tarFlux,num_IC,nT,cov,rep);

    % Predict flux with machine learning
    featureMatrix_AutoGenerateTrain_meta_1contMet(3,regListIndex) = feature_predictFlux_1contMet_median(autogen_meta_prefix,met1,tarFlux,num_IC,nT,cov,rep);

    % CoV of metabolite vs flux data
    featureMatrix_AutoGenerateTrain_meta_1contMet(4,regListIndex) = feature_cov_1contMet_median(autogen_meta_prefix,met1,tarFlux,num_IC,nT,cov,rep);
end
featureMatrix_AutoGenerateTrain_meta_1contMet_n = normalize(featureMatrix_AutoGenerateTrain_meta_1contMet,2,'range');

% Chass feature matrix
for regListIndex = 1:length(ChassMA_1contMet_List)

    tarFlux = ChassMA_1contMet_List(regListIndex,end);
    met1 = ChassMA_1contMet_List(regListIndex,1);
    
    % Correlation of single metabolite with target flux
    featureMatrix_1contMet_Chass(1,regListIndex) = feature_correlation_1contMet_median(Chass_prefix,met1,tarFlux,num_IC,nT,cov,rep);

    % Curve fit adjusted R2
    featureMatrix_1contMet_Chass(2,regListIndex) = feature_curveFit_1contMet_median(Chass_prefix,met1,tarFlux,num_IC,nT,cov,rep);

    % Predict flux with machine learning
    featureMatrix_1contMet_Chass(3,regListIndex) = feature_predictFlux_1contMet_median(Chass_prefix,met1,tarFlux,num_IC,nT,cov,rep);

    % CoV of metabolite vs flux data
    featureMatrix_1contMet_Chass(4,regListIndex) = feature_cov_1contMet_median(Chass_prefix,met1,tarFlux,num_IC,nT,cov,rep);
end
featureMatrix_1contMet_Chass_n = normalize(featureMatrix_1contMet_Chass,2,'range');
