% Autogenerated data feature matrix
for regListIndex = 1:length(train_true_regs_1contMet) 

    tarFlux = regListIndex;
    met1 = 1+2*(regListIndex-1);
    
    % Correlation of single metabolite with target flux
    featureMatrix_AutoGenerateTrain_1contMet(1,regListIndex) = feature_correlation_1contMet(autogen_prefix,met1,tarFlux,num_IC,rep);

    % Curve fit adjusted R2
    featureMatrix_AutoGenerateTrain_1contMet(2,regListIndex) = feature_curveFit_1contMet(autogen_prefix,met1,tarFlux,num_IC,rep);

    % Predict flux with machine learning
    featureMatrix_AutoGenerateTrain_1contMet(3,regListIndex) = feature_predictFlux_1contMet(autogen_prefix,met1,tarFlux,num_IC,rep);

    % CoV of metabolite vs flux data
    featureMatrix_AutoGenerateTrain_1contMet(4,regListIndex) = feature_cov_1contMet(autogen_prefix,met1,tarFlux,num_IC,rep);
end
featureMatrix_AutoGenerateTrain_1contMet_n = normalize(featureMatrix_AutoGenerateTrain_1contMet,2,'range');

% Second autogenerated data feature matrix
for regListIndex = 1:length(train_true_regs_meta_1contMet) 

    tarFlux = regListIndex;
    met1 = 1+2*(regListIndex-1);
    
    % Correlation of single metabolite with target flux
    featureMatrix_AutoGenerateTrain_meta_1contMet(1,regListIndex) = feature_correlation_1contMet(autogen_meta_prefix,met1,tarFlux,num_IC,rep);

    % Curve fit adjusted R2
    featureMatrix_AutoGenerateTrain_meta_1contMet(2,regListIndex) = feature_curveFit_1contMet(autogen_meta_prefix,met1,tarFlux,num_IC,rep);

    % Predict flux with machine learning
    featureMatrix_AutoGenerateTrain_meta_1contMet(3,regListIndex) = feature_predictFlux_1contMet(autogen_meta_prefix,met1,tarFlux,num_IC,rep);

    % CoV of metabolite vs flux data
    featureMatrix_AutoGenerateTrain_meta_1contMet(4,regListIndex) = feature_cov_1contMet(autogen_meta_prefix,met1,tarFlux,num_IC,rep);
end
featureMatrix_AutoGenerateTrain_meta_1contMet_n = normalize(featureMatrix_AutoGenerateTrain_meta_1contMet,2,'range');

% Hynne feature matrix
for regListIndex = 1:length(HynneMA_1contMet_List)

    tarFlux = HynneMA_1contMet_List(regListIndex,end);
    met1 = HynneMA_1contMet_List(regListIndex,1);
    
    % Correlation of single metabolite with target flux
    featureMatrix_1contMet_Hynne(1,regListIndex) = feature_correlation_1contMet(Hynne_prefix,met1,tarFlux,num_IC,rep);

    % Curve fit adjusted R2
    featureMatrix_1contMet_Hynne(2,regListIndex) = feature_curveFit_1contMet(Hynne_prefix,met1,tarFlux,num_IC,rep);

    % Predict flux with machine learning
    featureMatrix_1contMet_Hynne(3,regListIndex) = feature_predictFlux_1contMet(Hynne_prefix,met1,tarFlux,num_IC,rep);

    % CoV of metabolite vs flux data
    featureMatrix_1contMet_Hynne(4,regListIndex) = feature_cov_1contMet(Hynne_prefix,met1,tarFlux,num_IC,rep);
end
featureMatrix_1contMet_Hynne_n = normalize(featureMatrix_1contMet_Hynne,2,'range');
